import type { Category, Product } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  { id: "cerveza", name: "Cerveza", icon: "🍺", order: 0, isActive: true },
  { id: "gaseosa", name: "Gaseosa", icon: "🥤", order: 1, isActive: true },
];

export const MOCK_PRODUCTS: Product[] = [
  // Cerveza
  {
    id: "1",
    name: "Poker Six-Pack 330ml",
    description: "Cerveza colombiana, rubia, suave",
    categoryId: "cerveza",
    presentation: "SIXPACK",
    regularPrice: 22000,
    promoPrice: 17500,
    stock: 8,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Corona Six-Pack 355ml",
    description: "Cerveza mexicana, clara, premium",
    categoryId: "cerveza",
    presentation: "SIXPACK",
    regularPrice: 32000,
    promoPrice: 25900,
    stock: 5,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "BBC Stout 330ml",
    description: "Cerveza negra artesanal",
    categoryId: "cerveza",
    presentation: "BOTTLE",
    regularPrice: 8500,
    promoPrice: 6200,
    stock: 12,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Club Colombia Six-Pack",
    description: "Cerveza premium colombiana",
    categoryId: "cerveza",
    presentation: "SIXPACK",
    regularPrice: 28000,
    promoPrice: 22500,
    stock: 3,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "Redds Six-Pack 350ml",
    description: "Cerveza roja premium",
    categoryId: "cerveza",
    presentation: "SIXPACK",
    regularPrice: 26000,
    promoPrice: 19900,
    stock: 6,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Gaseosa
  {
    id: "6",
    name: "Coca-Cola Six-Pack 355ml",
    description: "Gaseosa clásica",
    categoryId: "gaseosa",
    presentation: "SIXPACK",
    regularPrice: 18000,
    promoPrice: 14200,
    stock: 15,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    name: "Pepsi 1.5L",
    description: "Gaseosa grande",
    categoryId: "gaseosa",
    presentation: "BOTTLE",
    regularPrice: 7500,
    promoPrice: 5500,
    stock: 20,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "Sprite Six-Pack 355ml",
    description: "Gaseosa de lima-limón",
    categoryId: "gaseosa",
    presentation: "SIXPACK",
    regularPrice: 17000,
    promoPrice: 13500,
    stock: 10,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    name: "Manzana Postobón 400ml",
    description: "Gaseosa de manzana colombiana",
    categoryId: "gaseosa",
    presentation: "BOTTLE",
    regularPrice: 5500,
    promoPrice: 3800,
    stock: 25,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "10",
    name: "Colombiana Six-Pack 335ml",
    description: "Gaseosa tradicional colombiana",
    categoryId: "gaseosa",
    presentation: "SIXPACK",
    regularPrice: 16000,
    promoPrice: 12500,
    stock: 8,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
